tap "auth0/auth0-cli"
tap "goreleaser/tap"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "planetscale/tap"
tap "supabase/tap"

brew "automake"
brew "bat"
brew "bison"
brew "chruby"
brew "deno"
brew "exa"
brew "fzf"
brew "gdbm"
brew "gh"
brew "openssl@1.1"
brew "readline"
brew "xz"
brew "python@3.10"
brew "git-filter-repo"
brew "git-lfs"
brew "go"
brew "golang-migrate"
brew "goreleaser"
brew "httpie"
brew "openssl@3", link: true
brew "iperf3"
brew "jq"
brew "jump"
brew "libffi"
brew "libyaml"
brew "lsd"
brew "mkcert"
brew "mysql-client"
brew "node"
brew "nss"
brew "pnpm"
brew "pyenv"
brew "rbenv"
brew "ripgrep"
brew "ruby"
brew "star"
brew "starship"
brew "tldr"
brew "transcrypt"
brew "tree"
brew "zoxide"
brew "hashicorp/tap/terraform"
brew "planetscale/tap/pscale"
brew "supabase/tap/supabase"

####################
## Casks           #
####################
cask "1password"
cask "chromium"
cask "docker"
cask "finicky"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "github"
cask "google-chrome"
cask "gh"
cask "google-cloud-sdk"
cask "iterm2"
cask "ngrok"
cask "postman"
cask "raycast"
cask "typora"
cask "powershell"
cask "visual-studio-code"


####################
## Mac App Store   #
####################
mas "Magnet", id: 441258766
mas "Xcode", id: 497799835
